"""empty message

Revision ID: 8566b00120ea
Revises: cc909177aa42
Create Date: 2019-01-22 07:27:51.910469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8566b00120ea'
down_revision = 'cc909177aa42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
